// Bundles the Material Web components and Material Symbols icons the app uses into vendor/material.js,
// so the site and the single-file build work offline with no CDN. Run: npm run vendor
import { build } from 'esbuild';
import { readFileSync } from 'node:fs';

const COMPONENTS = [
  'button/filled-button', 'button/filled-tonal-button', 'button/outlined-button', 'button/text-button',
  'iconbutton/icon-button', 'icon/icon', 'dialog/dialog', 'textfield/outlined-text-field',
  'progress/linear-progress', 'menu/menu', 'menu/menu-item', 'ripple/ripple', 'focus/md-focus-ring', 'divider/divider',
  'labs/segmentedbutton/outlined-segmented-button', 'labs/segmentedbuttonset/outlined-segmented-button-set',
];
const ICONS = ['settings', 'add', 'playlist_add', 'edit', 'delete', 'arrow_back', 'more_vert', 'play_arrow',
  'menu_book-fill', 'replay', 'arrow_forward', 'download', 'upload', 'cloud_download', 'workspace_premium-fill',
  'format_list_bulleted'];

const icons = Object.fromEntries(ICONS.map(name => {
  const svg = readFileSync(`node_modules/@material-symbols/svg-400/rounded/${name}.svg`, 'utf8');
  return [name.replace(/-fill$/, ''), svg.match(/<path d="([^"]+)"/)[1]];
}));

const entry = COMPONENTS.map(c => `import '@material/web/${c}.js';`).join('\n') +
  `\nwindow.MD_ICONS = ${JSON.stringify(icons)};\n`;

await build({
  stdin: { contents: entry, resolveDir: process.cwd() },
  bundle: true, minify: true, format: 'esm', outfile: 'vendor/material.js', legalComments: 'eof',
  banner: { js: '// Material Web + Material Symbols (Apache-2.0, Google). Generated by tools/build-vendor.mjs.' },
});
console.log('Wrote vendor/material.js');
