// Generates Material 3 color tokens (light + dark) for the green / gold / white palette.
// Run: node tools/gen-theme.mjs > theme.css
import { DynamicScheme, Hct, MaterialDynamicColors, TonalPalette, Variant, hexFromArgb, argbFromHex } from '@material/material-color-utilities';

const GREEN = argbFromHex('#2e6b45');
const GOLD = argbFromHex('#c9a227');
const hue = c => Hct.fromInt(c).hue;

const palettes = {
  primaryPalette: TonalPalette.fromHueAndChroma(hue(GREEN), 40),
  secondaryPalette: TonalPalette.fromHueAndChroma(hue(GREEN), 14),
  tertiaryPalette: TonalPalette.fromHueAndChroma(hue(GOLD), 48),
  neutralPalette: TonalPalette.fromHueAndChroma(hue(GREEN), 2),
  neutralVariantPalette: TonalPalette.fromHueAndChroma(hue(GREEN), 6),
};

const roles = Object.entries(MaterialDynamicColors)
  .filter(([k, v]) => v && typeof v.getArgb === 'function' && !/palette|keyColor/i.test(k));
const kebab = s => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

function tokens(isDark) {
  const scheme = new DynamicScheme({ sourceColorHct: Hct.fromInt(GREEN), variant: Variant.TONAL_SPOT, contrastLevel: 0, isDark, ...palettes });
  return roles.map(([k, v]) => `  --md-sys-color-${kebab(k)}: ${hexFromArgb(v.getArgb(scheme))};`).join('\n');
}

console.log(`/* Generated by tools/gen-theme.mjs — green primary, gold tertiary, near-white neutrals. */
:root {
${tokens(false)}
}
@media (prefers-color-scheme: dark) {
  :root {
${tokens(true).replace(/^/gm, '  ')}
  }
}`);
